language: python
python:
  - "3.7"      # current default Python on Travis CI
# command to install dependencies
install:
  - pip install irons
  - pip install numba==0.49.1
# command to run tests
script:
  - pytest